package helper

import (
	"golang.org/x/crypto/bcrypt"
)

// HashPassword generates a secure hash for a password using the bcrypt algorithm.
// bcrypt is the industry standard for storing passwords, and it automatically handles the generation and storage of salts.
//
// password: The plaintext password entered by the user.
// Returns: A bcrypt hash string that can be directly stored in the database.
func HashPassword(password string) (string, error) {
	// Use the GenerateFromPassword function, which automatically generates a salt and calculates the hash.
	// DefaultCost is a recommended computational strength that provides a balance between security and performance.
	bytes, err := bcrypt.GenerateFromPassword([]byte(password), bcrypt.DefaultCost)
	if err != nil {
		return "", err
	}
	return string(bytes), nil
}

// CheckPasswordHash compares a plaintext password with a bcrypt hash to see if they match.
//
// password: The plaintext password entered by the user during login.
// hash: The hash string read from the database, previously generated by HashPassword.
// Returns: true if the password matches.
func CheckPasswordHash(password, hash string) bool {
	// CompareHashAndPassword securely handles all comparison logic.
	// It automatically extracts the salt from the hash and performs the comparison.
	err := bcrypt.CompareHashAndPassword([]byte(hash), []byte(password))
	// If err is nil, it means the password matches.
	return err == nil
}
